[settings]
experimental = true
pipx_uvx = true
go_set_gobin = true
idiomatic_version_file_enable_tools = ["java"]

[tools]
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"pipx:git-delete-merged-branches" = "latest"
"pipx:ruff" = "latest"
"github:aristocratos/btop" = "latest"
"github:golangci/golangci-lint" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:jj-vcs/jj" = "latest"
"github:quodlibetor/git-instafix" = "latest"
"github:quodlibetor/s3glob" = "latest"
"github:terrastruct/d2" = "latest"
"github:tummychow/git-absorb" = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
java = "17"
jj = "latest"
jjui = "latest"
jq = "latest"
k9s = "latest"
node = "23.1.0"
python = "3.14"
ripgrep = { version = "latest", exe = "rg" }
shellcheck = "latest"
starship = "latest"
zoxide = "latest"
